/*  src/types.ts
 *
 *  Public DTO & Command‑Model layer for the REST API.
 *  All types are derived – whenever possible – from the database
 *  declaration generated by `supabase` (see database.types.ts for the
 *  full `Tables`, `TablesInsert`, `TablesUpdate` helper utilities).
 *
 *  The intent is:
 *    • keep a single‑source‑of‑truth (the DB schema),
 *    • avoid repetition of columns,
 *    • expose only the fields the HTTP API is allowed to reveal.
 *  ──────────────────────────────────────────────────────────────── */

/* ─────────────────────────── Helpers ──────────────────────────── */

export type PaginationMeta = {
  limit: number
  offset: number
  total: number
}

export type WithPagination<T> = {
  data: ReadonlyArray<T>
  pagination: PaginationMeta
}

/* ────────────────────── User‑Profile ( /users ) ───────────────── */

/**
 * There is no “users” table inside the `public` schema – Supabase keeps it
 * in the
 * `auth` schema that is not generated into our typings.  Therefore the DTO
 * is handwritten.
 */
export type UserProfileDTO = {
  id: string
  email: string
  created_at: string
  last_login_at: string | null
}

/** PATCH /users/me – currently only system‑driven, but still typed */
export type UpdateUserProfileCommand = Partial<Pick<UserProfileDTO, 'last_login_at'>>

/* ──────────────────────── Flashcards ─────────────────────────── */

import type { Tables, TablesInsert, TablesUpdate } from './db/database.types' // path‑alias to generated file

/** Raw DB row */
export type FlashcardRow = Tables<'flashcards'>

/** Public representation used in list / detail endpoints */
export type FlashcardDTO = Omit<FlashcardRow, 'user_id'>

export type FlashcardSummaryDTO = Pick<FlashcardRow, 'id' | 'question' | 'answer'>

/* ---------- Commands ---------- */

/** GET /flashcards – query parameters (all optional) */
export type FlashcardListQuery = {
  limit?: number                  // 1 … 100  (server defaults 20)
  offset?: number                 // ≥ 0       (default 0)
  search?: string
  ai_generated?: boolean
  ai_status?: 0 | 1 | 2 | null
  difficulty?: 0 | 1 | 2 | 3 | 4 | 5
  due?: boolean                   // true → next_review_at ≤ NOW()
  sort?: 'created_at' | 'next_review_at'
  order?: 'asc' | 'desc'
  ids?: string                    // comma‑separated UUID list
}

/** POST /flashcards/generate/manual */
export type CreateManualFlashcardCommand = Pick<
  TablesInsert<'flashcards'>,
  'question' | 'answer'
> & {
  difficulty?: number
}

/** POST /flashcards/generate/ai */
export type GenerateAiCardsCommand = {
  source_text: string
  desired_count?: number
}

/** PATCH /flashcards/{id} */
export type UpdateFlashcardCommand = Partial<
  Pick<TablesUpdate<'flashcards'>, 'question' | 'answer' | 'difficulty'>
>

/** DELETE /flashcards?ids=… */
export type DeleteFlashcardsCommand = {
  ids: string[] // already split into an array by the controller layer
}

/* ---------- Endpoint responses ---------- */

export type FlashcardListResponse = WithPagination<FlashcardDTO>

export type CreateManualFlashcardResponse = FlashcardDTO

export type GenerateAiCardsResponse = {
  generated: ReadonlyArray<FlashcardSummaryDTO>
}

export type UpdateFlashcardResponse = FlashcardDTO

export type DeleteFlashcardsResponse = {
  deleted_ids: string[]
  message: string
}

/** Returned by both /accept and /reject */
export type FlashcardAiStatusDTO = Pick<FlashcardRow, 'id' | 'ai_status'>

/* ──────────────────────── AI Metrics ─────────────────────────── */

export type AiMetricsRow = Tables<'ai_metrics'>

export type AiMetricsDTO = AiMetricsRow & {
  /** acceptance_rate = (accepted_cnt / generated_cnt) * 100 */
  acceptance_rate: number
}